#!/usr/bin/perl -w
use strict;
use DBI;
use POSIX;
use JSON;
use Data::Dumper;
use LWP::UserAgent;
use File::Path;

#设定文件存储路径
my $dstPath = "/home/runtime/data/mb";
my $dataPath = $dstPath . '/file';
#设定MySQL数据库参数
my $db_name = 'feng';
my $db_host = '192.168.0.15';
my $db_user = 'devp';
my $db_pass = 'fxf.devp';

my $dsn = "DBI:mysql:database=$db_name;host=$db_host";
my $conn = DBI->connect($dsn, $db_user, $db_pass) or die "don't connect MySQL.";
$conn->do("SET NAMES 'utf8'");
my $nStart = 10160001;
my $count = 2000;
for(my $i = 0; $i < $count; $i++) {
	my $mid = $nStart + $i;
	my $no = $mid % 8;
	my $query = "insert into kongma_info_${no} (id,type,content) values(?,14,?)";
	my $sth = $conn->prepare($query);
	my $json = '{"pageList":[{"mediaUrl":"http://img2.ifengzi.cn/mc/view.php?id=8806971a-31b5-4e75-882e-13edc4529cee&type=jpg","picType":0,"soundUrl":"http://img1.ifengzi.cn/mc/view.php?id=f069ef46-66ed-45cd-b145-e1eebd71ff90&type=mp3","textContent":"“做雷锋式的一滴水”，我们每个人都是“雷锋”。当您开车上下班看到路边焦急等待的路人，请您打开车门。一个举动，一份爱心。","tinypicUrl":""}],"title":"顺风车一起来，有你更精彩！","totalCount":1}';	
	my $result = $sth->execute(($mid, $json));
	if (!$result) {
		print "$no -> $mid: ERROR\n";
        } else {
        	print "$no -> $mid: OK\n";
        }
}

print "\n";

1;
